### ISSUE TITLE
cannot use angular-moment under webpack

### ISSUE THREAD

**Issue by kimcmich** [urish/angular-moment#108]
I'm running an angular app under webpack-dev-server that includes moment and angular moment. My basic config file stars as:

```javascript
var app;

require("jquery");
require("angular");
require("ui_router");
require("facebook");
require("bootstrap_css");
require("index_scss");
require("ui_bootstrap");
require("angular_mocks");
require("angular_sanitize");
require("moment");
require("angular_moment");

mockApp = angular.module('mockApp', ['sp.app', 'ngMockE2E'])
.run (['$httpBackend',
    function($httpBackend) {
        server_url = 'https://dev.sharepractice.com';
        $httpBackend.whenGET(server_url + '/api/v1/specialties_list')
            .respond({
                results: ['Voodoo', 'Acupuncture and Oriental Medicine', 'Addiction Medicine', 'Functional Medicine']
            });
        $httpBackend.whenGET(/.*/).passThrough();
        $httpBackend.whenPOST(/.*/).passThrough();
    }
]);

app = angular.module("sp.app", ['ui.router', 'ui.bootstrap', 'facebook', 'mockApp', 'ngSanitize', 'angularMoment'])
```

I get a javascript error when angular-moment loads that "angular.moment" is not a function.

I investigated this and found that, for some reason, when angular-moment is intializing, the passed in value for angular is an empty object (not null/undefined but an empty object). I fixed the problem in my local source for angular-moment by adding a check for an empty angular object at which point I assign angular the value of window.angular (which does exist). This fixes the issue, but, as is, angular-moment will not work with my app otherwise...

My modification:
before the line #20 in angular-moment.js v0.9.0, I insert this block

```javascript
var angularAvailable = false;
for (prop in angular) {
	angularAvailable = true;
}

if (!angularAvailable) {
	angular = window.angular;
}
```

**Comment by kumarharsh** [comment]
You can make the module work by using this webpack config in your source code:

```
function absPath(_path) {
  return path.join(__dirname, _path);
}

"angular-moment": {path: absPath('node_modules/angular-moment/angular-moment.js'), imports: ['define=>false', 'angular', 'moment']},
```

and using webpack's [imports-loader](https://github.com/webpack/imports-loader) loader. The trick is setting the `define` as false, so that the *broken* define is not run, instead the module.exports part is run.

**Comment by cbfx** [comment]
@kumarharsh thanks for the help on this issue. i'm new to webpack but am running into this issue, unfortunately. could you give me an example of where the 'angular-moment' key needs to go in a config file and a little explanation on it? thanks in advance.

**Comment by cbfx** [comment]
@kumarharsh i've resolved the issue on my end by adding this:

```javascript
module: {
  loaders: [
    ...
    {test: /[\/]angular\.js$/, loader: "exports?angular"}
  ]
}
```

**Comment by urish** [comment]
Should be fixed here:

https://github.com/urish/angular-moment/blob/8b34525d33e61070e10c1b2b6ae386de5021c9ec/angular-moment.js#L651

Please check and report back!

Thanks :)

**Comment by voor** [comment]
Webpack still hits the first part:
```
if (typeof define === 'function' && define.amd) {
		define(['angular', 'moment'], angularMoment);
```
And breaks with the same error message of `Uncaught TypeError: angular.module is not a function`

The compiled WEBPACK shows this:
```
if (true) {
			!(__WEBPACK_AMD_DEFINE_ARRAY__ = [__webpack_require__(3), __webpack_require__(26)], __WEBPACK_AMD_DEFINE_FACTORY__ = (angularMoment), __WEBPACK_AMD_DEFINE_RESULT__ = (typeof __WEBPACK_AMD_DEFINE_FACTORY__ === 'function' ? (__WEBPACK_AMD_DEFINE_FACTORY__.apply(exports, __WEBPACK_AMD_DEFINE_ARRAY__)) : __WEBPACK_AMD_DEFINE_FACTORY__), __WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));
		
```
Which means it's definitely executing the first function instead of the second.

**Comment by fvelosa** [comment]
Hi, I also get the same error even after upgrading to 1.0.0-beta.2 `Uncaught TypeError: angular.module is not a function.

**Comment by luisfontes** [comment]
Same here on 1.0.0-beta.2

**Comment by urish** [comment]
Alright, I want to get this fixed for `1.0.0-beta.3`.

Can you please check if switching the order of the if statements help?

i.e.

```javascript
if (typeof module !== 'undefined' && module && module.exports) {
    angularMoment(require('angular'), require('moment'));
    module.exports = 'angularMoment';
} else if (typeof define === 'function' && define.amd) {
    define(['angular', 'moment'], angularMoment);
} else {
     angularMoment(angular, (typeof global !== 'undefined' ? global : window).moment);
}
```

**Comment by luisfontes** [comment]
I've pasted your code and got the same error. I managed to get it working with this `if` block:

```javascript
	if (typeof module !== 'undefined' && module && module.exports) {
	    angularMoment(angular, moment);
	    module.exports = 'angularMoment';
	} else if (typeof define === 'function' && define.amd) {
	    define(['angular', 'moment'], angularMoment);
	} else {
	    angularMoment(angular, (typeof global !== 'undefined' ? global : window).moment);
	}
```

**Comment by urish** [comment]
@luisfontes thanks a million! can you please paste your webpack configuration? or even better, make a small gist / github repo that reproduces this?

Thanks!

**Comment by laggingreflex** [comment]
Having this issue too.

    Uncaught TypeError: angular.module is not a function

        angularMoment        @ angular-moment.js:18
        (anonymous function) @ angular-moment.js:625
        (anonymous function) @ angular-moment.js:632
        __webpack_require__  @ bootstrap a227ebb9e9efcc5c6178:19
        (anonymous function) @ webpack-entry-vendor.js:11
        __webpack_require__  @ bootstrap a227ebb9e9efcc5c6178:19
        (anonymous function) @ webpack-entry-verdor.js:3
        __webpack_require__  @ bootstrap a227ebb9e9efcc5c6178:19
        (anonymous function) @ webpack-entry.js:2
        __webpack_require__  @ bootstrap a227ebb9e9efcc5c6178:19
        (anonymous function) @ bootstrap a227ebb9e9efcc5c6178:39
        (anonymous function) @ bootstrap a227ebb9e9efcc5c6178:39

I inspected the relevant line (625): 

    if (typeof define === 'function' && define.amd) {
        define(['angular', 'moment'], angularMoment); << line:625
    } else if (typeof module !== 'undefined' && module && module.exports) {

to see what Webpack does to it, and it appears it changes it in this way:

    if (true) {
        !(__WEBPACK_AMD_DEFINE_ARRAY__ = [__webpack_require__(297), __webpack_require__(196)], __WEBPACK_AMD_DEFINE_FACTORY__ = (angularMoment), __WEBPACK_AMD_DEFINE_RESULT__ = (typeof __WEBPACK_AMD_DEFINE_FACTORY__ === 'function' ? (__WEBPACK_AMD_DEFINE_FACTORY__.apply(exports, __WEBPACK_AMD_DEFINE_ARRAY__)) : __WEBPACK_AMD_DEFINE_FACTORY__), __WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));
    } else if (typeof module !== 'undefined' && module && module.exports) {

(I'm new to webpack, so I'm gussing this is intended?) 

At any rate this is probably where the problem lies.

**Comment by laggingreflex** [comment]
Facing this exact same issue in other angular modules as well (angular-storage, angular-translate), [even angular itself!](http://i.imgur.com/bV0B4Pd.png) All errors are on the line where Webpack replaces the define statement (as stated by @voor [above](https://github.com/urish/angular-moment/issues/108#issuecomment-144480550)).

**Comment by pavel06081991** [comment]
have the same problem.

**Comment by timc13** [comment]
+1

**Comment by vogloblinsky** [comment]
+1
Uni testing using theintern fails with define block.

**Comment by ace-han** [comment]
+1

**Comment by aaweb** [comment]
+1

**Comment by readme42** [comment]
+1

**Comment by Mikaeru001** [comment]
Got it working by applying exports-loader to angular.js file. It is the same solution as @cbfx has suggested. No need to inject `define=>false` with imports-loader.

webpack.config.js:
```
...
module: {
  loaders: [
    { test: path.resolve('./app/bower_components/angular/angular.js'), loader: 'exports?angular'},
    ...
  ]
}
...
```

**Comment by gregorskii** [comment]
This is not working for me regardless of the workarounds in this ticket.

I am not using loaders. I am trying it directly in the require statement:

```
require('exports?$!exports?jQuery!expose?$!expose?jQuery!jquery');
require('exports?angular!angular');
require('imports?angular!angular-moment');
```

I have tried the loaders in the webpack config, I have also tried with and without imports?angular on angular-moment.

The project I am working on is using a pretty old version of angular. I have also tried updating angular and that does not work either.

It is currently using Angular 1.2.20, I would prefer to not have to introduce other breaking changes. But I have tried updating all of my bower and npm packages completely. This did not help either.

I am currently using these packages:

bower:

```
"dependencies": {
    "angular": "~1.2.20",
    "jquery": "~2.1.1",
    "angular-resource": "~1.2.20",
    "angular-cookies": "~1.2.20",
    "angular-sanitize": "~1.2.20",
    "angular-route": "~1.2.20",
    "angular-underscore-module": "~1.0.3",
    "underscore": "~1.6.0",
    "ngstorage": "~0.3.0",
    "angular-bootstrap": "~0.11.0",
    "angular-ui-router": "~0.2.11",
    "angular-upload": "~1.0.11",
    "bootstrap-sass-official": "~3.2.0",
    "jasny-bootstrap": "3.2.0-beta.1",
    "angular-chosen-localytics": "~1.0.6",
    "tinymce": "^4.3.8"
  },
  "devDependencies": {
    "angular-mocks": "~1.2.20",
    "angular-scenario": "~1.2.20"
  }
```

NPM:

```
  "devDependencies": {
    "bower-webpack-plugin": "^0.1.9",
    "browser-sync": "^2.9.1",
    "css-loader": "^0.23.1",
    "del": "^2.0.1",
    "exports-loader": "^0.6.3",
    "expose-loader": "^0.7.1",
    "file-loader": "^0.8.5",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^3.0.0",
    "gulp-changed": "^1.3.0",
    "gulp-concat-util": "^0.5.5",
    "gulp-eslint": "^2.0.0",
    "gulp-if": "^2.0.0",
    "gulp-minify-css": "^1.2.1",
    "gulp-notify": "^2.2.0",
    "gulp-plumber": "^1.0.1",
    "gulp-rename": "^1.2.2",
    "gulp-replace": "^0.5.4",
    "gulp-sass": "^2.0.4",
    "gulp-sequence": "^0.4.1",
    "gulp-shopify-upload": "^2.0.0",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-uglify": "^1.5.3",
    "gulp-debug": "^2.1.2",
    "gulp-util": "^3.0.6",
    "gulp-watch": "^4.3.5",
    "jsdoc": "^3.3.2",
    "jsonfile": "^2.2.1",
    "lodash": "^4.5.1",
    "ng-annotate-webpack-plugin": "^0.1.2",
    "pretty-hrtime": "^1.0.2",
    "raw-loader": "^0.5.1",
    "require-dir": "^0.3.0",
    "style-loader": "^0.13.0",
    "through2": "^2.0.0",
    "vinyl-named": "^1.1.0",
    "webpack": "^1.12.14",
    "webpack-stream": "^3.1.0"
  },
  "dependencies": {
    "angular-moment": "^1.0.0-beta.5",
    "imports-loader": "^0.6.5",
    "moment": "^2.12.0",
    "phoneformat": "0.0.7"
  }
```

**Comment by gregorskii** [comment]
Update:

This is the only config that worked for me (only relative parts shown):

```
loaders: [
    {test: /[\/]angular\.js$/, exclude: ['/bower_components/'], loader: 'exports?angular'},
]
```

```
new webpack.ProvidePlugin({
    '$': 'jquery',
    'jQuery': 'jquery',
    'window.jQuery': 'jquery',
    'moment': 'moment'
})
```

**Comment by enricop89** [comment]
This is not working for me regardless of the commit `https://github.com/urish/angular-moment/commit/517f42fb2fbbfe0823cc7d8e667c4cce5a6cb317`
Is there a working configuration for this issue?

**Comment by adeptues** [comment]
This is still happening for me using version 1.0.0 the following code snippet appears to be the problem

`if (true) {
			!(__WEBPACK_AMD_DEFINE_ARRAY__ = [__webpack_require__(43), __webpack_require__(49)], __WEBPACK_AMD_DEFINE_FACTORY__ = (angularMoment), __WEBPACK_AMD_DEFINE_RESULT__ = (typeof __WEBPACK_AMD_DEFINE_FACTORY__ === 'function' ? (__WEBPACK_AMD_DEFINE_FACTORY__.apply(exports, __WEBPACK_AMD_DEFINE_ARRAY__)) : __WEBPACK_AMD_DEFINE_FACTORY__), __WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));
		} else if (typeof module !== 'undefined' && module && module.exports && (typeof require === 'function')) {
			module.exports = angularMoment(require('angular'), require('moment'));
		} else {
			angularMoment(angular, (typeof global !== 'undefined' ? global : window).moment);
		}`

Not sure why its always if(true) then with the webpack generated stuff
