### ISSUE TITLE
1.0.0-beta.6  Dont work with angular 1.5.5

### ISSUE THREAD

**Issue by meron1122** [urish/angular-moment#251]
On page load
> "Cannot find module 'angular'"

html:
`  
    <script src="../bower_components/angular/angular.min.js"></script>
    
    <script src="../bower_components/moment/min/moment.min.js"></script>
    <script src="../bower_components/angular-moment/angular-moment.js"></script>`

bower.json:
`  "dependencies": {
    "angular": "1.5.5",
    "moment": "^2.13.0",
    "angular-moment": "^1.0.0-beta.6"
  }`

**Comment by Totemika** [comment]
There must be some other reason why it's not working, I'm also using those versions and got no errors.

**Comment by ulion** [comment]
same and +1

**Comment by urish** [comment]
Sounds like a setup issue.

There have been some improvements to the UMD code. If the issue still happens, please open a new issue
